
#
# Ubuntu Node.js Dockerfile
#
# https://github.com/dockerfile/ubuntu/blob/master/Dockerfile
# https://docs.docker.com/examples/nodejs_web_app/
#

# Pull base image.
FROM ubuntu:14.04

# Install Node.js

RUN apt-get update
RUN apt-get install --yes curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
RUN apt-get install --yes nodejs
RUN apt-get install --yes build-essential
RUN npm i npm@latest -g

RUN apt-get install --yes git-core

RUN npm install --global gatsby-cli

#WORKDIR /home
RUN mkdir /src
WORKDIR /src
RUN gatsby new gatsby-site
WORKDIR  /src/gatsby-site
#RUN  gatsby develop &>/dev/null

#WORKDIR /src/gatsby-site



# Bundle app source
# Trouble with COPY http://stackoverflow.com/a/30405787/2926832
#COPY . /src

# Install app dependencies
#RUN cd /src; npm install

# Binds to port 80000
EXPOSE  8000

#  Defines your runtime(define default command)
# These commands unlike RUN (they are carried out in the construction of the container) are run when the container
#CMD ["node", "/src/index.js"]

ENTRYPOINT ["gatsby","develop","--host","0.0.0.0","--port","8000","&>/dev/null"]
